-- =========================================================
-- Media Tracker - Database Schema
-- Run this entire script in your Oracle SQL worksheet
-- (connected as the media_app user) to create all tables.
-- =========================================================

-- Genres (e.g. "Drama", "Comedy", "Sci-Fi")
CREATE TABLE genres (
    genre_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(50) NOT NULL UNIQUE
);

-- Media: a single row represents either a Movie or a Show
CREATE TABLE media (
    media_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR2(255) NOT NULL,
    media_type   VARCHAR2(10) NOT NULL CHECK (media_type IN ('MOVIE','SHOW')),
    release_year NUMBER(4),
    overview     VARCHAR2(4000),
    poster_url   VARCHAR2(500),
    tmdb_id      NUMBER,                          -- links to TMDB's own ID, used later in Phase 6
    created_at   DATE DEFAULT SYSDATE NOT NULL
);

-- Many-to-many bridge table: one Media item can have several Genres,
-- and one Genre can apply to many Media items.
CREATE TABLE media_genres (
    media_id  NUMBER NOT NULL REFERENCES media(media_id) ON DELETE CASCADE,
    genre_id  NUMBER NOT NULL REFERENCES genres(genre_id) ON DELETE CASCADE,
    PRIMARY KEY (media_id, genre_id)
);

-- Seasons only apply to Media rows where media_type = 'SHOW'
CREATE TABLE seasons (
    season_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id      NUMBER NOT NULL REFERENCES media(media_id) ON DELETE CASCADE,
    season_number NUMBER NOT NULL,
    title         VARCHAR2(255),
    CONSTRAINT uq_season UNIQUE (media_id, season_number)
);

-- Episodes belong to a Season
CREATE TABLE episodes (
    episode_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id      NUMBER NOT NULL REFERENCES seasons(season_id) ON DELETE CASCADE,
    episode_number NUMBER NOT NULL,
    title          VARCHAR2(255),
    air_date       DATE,
    CONSTRAINT uq_episode UNIQUE (season_id, episode_number)
);

-- Tracks your overall status per Media item (one row per Media item)
CREATE TABLE watch_status (
    watch_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id        NUMBER NOT NULL UNIQUE REFERENCES media(media_id) ON DELETE CASCADE,
    status          VARCHAR2(20) NOT NULL
                      CHECK (status IN ('PLAN_TO_WATCH','WATCHING','COMPLETED','DROPPED')),
    updated_at      DATE DEFAULT SYSDATE NOT NULL
);

-- Tracks which individual episodes have been watched (for shows)
CREATE TABLE episode_progress (
    episode_id  NUMBER NOT NULL REFERENCES episodes(episode_id) ON DELETE CASCADE,
    watched_at  DATE DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (episode_id)
);

-- Your rating/review once you've finished a Media item
CREATE TABLE ratings (
    rating_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id   NUMBER NOT NULL UNIQUE REFERENCES media(media_id) ON DELETE CASCADE,
    score      NUMBER(3,1) CHECK (score BETWEEN 0 AND 10),
    review     VARCHAR2(4000),
    rated_at   DATE DEFAULT SYSDATE NOT NULL
);